### ISSUE TITLE
Can we add 2 missing columns from worldmeters source?

### ISSUE THREAD

**Issue by clearsense** [theleadio/corona-web#55]
Those two columns
![image](https://user-images.githubusercontent.com/9950886/77825931-06c44780-7115-11ea-8154-b98ccdff75b1.png)
are missed in result of `/v3/stats/worldometer/country`.
If they exists in `worldmeters` table, than we can easy add them. I can make PR if someone can tell names of those columns in DB table.
I suppose it is someting like `death_cases_per_million_pop` and `first_case_date`

**Comment by xming13** [comment]
@clearsense where is the screenshot from?

**Comment by clearsense** [comment]
> @clearsense where is the screenshot from?

https://www.worldometers.info/coronavirus/

**Comment by clearsense** [comment]
@xming13 do you find it? Those columns are on the right in main table on https://www.worldometers.info/coronavirus/

**Comment by xming13** [comment]
Hi @clearsense we do have `death_cases_per_million_pop` in the database but is not exposed via API.
we are not storing `first_case_date` though.

**Comment by xming13** [comment]
Hi @clearsense, this PR https://github.com/theleadio/corona-web/pull/59 will add `death_cases_per_million_pop` to the API.

**Comment by clearsense** [comment]
Hi! @xming13 thanks. Tell please, when you plan merge dev to master with all those changes?

**Comment by xming13** [comment]
Hi @clearsense, it is live now

**Comment by clearsense** [comment]
> Hi @clearsense, it is live now

Yeah, I checked it now and there is new param.
But there is problem with #37 When I try request with `date` param
http://api.coronatracker.com/v3/stats/worldometer/country?date=2020-03-25
it returns error
```{
    "status": 500,
    "message": "An error has occurred."
}```
Can you please check logs?

**Comment by clearsense** [comment]
@xming13 I found at least one issue, see PR #61
